#!/bin/bash

docker run -d -p 43306:3306 \
    --name db-mysql-sandbox \
    --network dealnews \
    -e MYSQL_ROOT_PASSWORD=percona-root \
    -e MYSQL_DATABASE=mytestdb \
    -e MYSQL_USER=test \
    -e MYSQL_PASSWORD=test \
    percona:5.7
