#!/bin/bash

docker run -d -p 55432:5432 \
    --name db-pgsql-sandbox \
    --network dealnews \
    -e POSTGRES_DB=pgtestdb \
    -e POSTGRES_USER=test \
    -e POSTGRES_PASSWORD=test \
    postgres:latest
